name: Release
on:
  push:
    branches: [ ci-debug ]
  pull_request:
    branches: [ ci-debug ]

jobs:

  build-on-ubuntu2204:
    runs-on: ubuntu-22.04
    name: build on ubuntu-22.04 x86_64
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'
      - name: Install Compilers
        run: |
          sudo apt-get update
          sudo apt-get install --yes build-essential pkgconf libelf-dev llvm clang linux-tools-common linux-tools-generic gcc gcc-aarch64-linux-gnu linux-source
          echo '................ nop begin'
          set -x
          for tool in "clang" "llc" "llvm-strip"
          do
            type $tool && $tool --version && ls -ahl /usr/bin/$tool || echo 'none?'
            [ -f /usr/bin/$tool-14 ] && ls -ahl /usr/bin/$tool-14
            sudo rm -f /usr/bin/$tool
            sudo ln -s /usr/bin/$tool-14 /usr/bin/$tool
          done
          set +x
          echo '..................unless op end'
          #cd /usr/src
          source_file=$(find /usr/src -maxdepth 1 -name "*linux-source*.tar.bz2")
          source_dir=${source_file%.tar*}
          #sudo tar -xf $source_file
          src_version=${source_dir#*src/}
          tar -xf $source_file -C .
          cd $src_version
          test -f .config || make oldconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- prepare V=0
        shell: bash
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: authenticate
        run: |
          gh auth login --with-token <<<'${{ secrets.GITHUB_TOKEN }}'
      - name: Release amd64
        run: |
          make clean
          export KERN_SRC_PATH=$(ls linux-source-*)
          make env
          make -f builder/Makefile.release release SNAPSHOT_VERSION=${{ github.ref_name }}
      - name: Release arm64 (CROSS COMPILATION)
        run: |
          make clean
          export KERN_SRC_PATH=$(ls linux-source-*)
          make env
          CROSS_ARCH=arm64 make -f builder/Makefile.release release SNAPSHOT_VERSION=${{ github.ref_name }}
      - name: Publish
        run: |
          make -f builder/Makefile.release publish SNAPSHOT_VERSION=${{ github.ref_name }}