name: Release
on:
  push:
    branches: [ ci-debug ]
  pull_request:
    branches: [ ci-debug ]

jobs:

  build-on-ubuntu2204:
    runs-on: ubuntu-22.04
    name: build on ubuntu-22.04 x86_64
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'
      - name: Install Compilers
        run: |
          sudo apt-get update
          kernel_ver=`uname -r | cut -d'-' -f 1`
          sudo apt-get install --yes build-essential pkgconf libelf-dev llvm clang linux-tools-common linux-tools-generic gcc gcc-aarch64-linux-gnu linux-source-${kernel_ver}
          echo '................ nop begin'
          set -x
          for tool in "clang" "llc" "llvm-strip"
          do
            type $tool && $tool --version && ls -ahl /usr/bin/$tool || echo 'none?'
            [ -f /usr/bin/$tool-14 ] && ls -ahl /usr/bin/$tool-14
            sudo rm -f /usr/bin/$tool
            sudo ln -s /usr/bin/$tool-14 /usr/bin/$tool
          done
          set +x
          echo '..................unless op end'
          # cd /usr/src
          # sudo tar -xf linux-source-${kernel_ver}.tar.bz2
          # cd /usr/src/linux-source-${kernel_ver}
          tar -xf /usr/src/linux-source-${kernel_ver}.tar.bz2
          cd linux-source-${kernel_ver}
          test -f .config || make oldconfig
          find -name kconfig.h
          echo ?!
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- prepare V=0
          ls -ahl
        shell: bash
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: authenticate
        run: |
          gh auth login --with-token <<<'${{ secrets.GITHUB_TOKEN }}'
      - name: Release amd64
        run: |
          make clean
          make env
          find -name kconfig.h
          echo ...??!!!
          make -f builder/Makefile.release release SNAPSHOT_VERSION=${{ github.ref_name }}
      - name: Release arm64 (CROSS COMPILATION)
        run: |
          kernel_ver=`uname -r | cut -d'-' -f 1`
          make clean
          make env KERN_SRC_PATH=linux-source-${kernel_ver}
          CROSS_ARCH=arm64 make -f builder/Makefile.release release KERN_SRC_PATH="linux-source-${kernel_ver}" SNAPSHOT_VERSION=${{ github.ref_name }}
      - name: Publish
        run: |
          make -f builder/Makefile.release publish SNAPSHOT_VERSION=${{ github.ref_name }}